export const CREATE_SUBSCRIPTION = "CREATE_SUBSCRIPTION";
export const UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION";
export const DELETE_SUBSCRIPTION = "DELETE_SUBSCRIPTION";
export const FETCH_SUBSCRIPTIONS = "FETCH_SUBSCRIPTIONS";
export const GET_DISTANCE_MATRIX = "GET_DISTANCE_MATRIX";
export const GET_FARE = "GET_FARE";
